# Generated by Django 6.1.1 on 2026-09-13 17:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory_manager",
            "0002_alter_order_discount_amount_alter_order_order_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-is_bestseller", "-created_at"]},
        ),
        migrations.AddField(
            model_name="category",
            name="image_url",
            field=models.CharField(
                blank=True, help_text="Optional banner image URL", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="craft_technique",
            field=models.CharField(
                blank=True,
                default="Traditional Handloom & Artisan Craft",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_bestseller",
            field=models.BooleanField(
                default=False, help_text="Mark as bestseller badge"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(
                default=True, help_text="Display on homepage featured section"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="material_origin",
            field=models.CharField(
                blank=True,
                default="100% Handcrafted in India",
                help_text="e.g. Chanderi, Madhya Pradesh",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="original_mrp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original MRP before discount",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                decimal_places=1, default=Decimal("4.8"), max_digits=3
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="review_count",
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, help_text="Delivery instructions"),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("UPI", "UPI / QR Code / Instant Pay"),
                    ("COD", "Cash on Delivery (COD)"),
                    ("CARD", "Credit / Debit Card"),
                    ("NET_BANKING", "Net Banking"),
                ],
                default="UPI",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "Pending Payment"),
                    ("PAID", "Paid Online"),
                    ("COD_PENDING", "Cash on Delivery (Pending)"),
                    ("REFUNDED", "Refunded"),
                ],
                default="UNPAID",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Order Placed"),
                    ("PROCESSING", "In Crafting / Packing"),
                    ("SHIPPED", "Dispatched / In Transit"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tax_rate_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.IntegerField(
                default=10, help_text="Current available quantity"
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=100)),
                ("rating", models.PositiveIntegerField(default=5)),
                ("comment", models.TextField()),
                ("is_verified_buyer", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="inventory_manager.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
